# Using Pandas

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("FAISS_text.csv")

In [7]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

# Convert Text to Vector

In [10]:
from sentence_transformers import SentenceTransformer

In [11]:
encoder = SentenceTransformer('all-mpnet-base-v2')

In [12]:
vectors = encoder.encode(df.text)

In [13]:
vectors

array([[-0.00247395,  0.03626721, -0.05290459, ..., -0.09152356,
        -0.03970002, -0.04330488],
       [-0.03357267,  0.00980517, -0.03250129, ..., -0.05165467,
         0.02245886, -0.03156182],
       [-0.01865323, -0.04051314, -0.01235387, ...,  0.00610585,
        -0.07179647,  0.02773853],
       ...,
       [-0.00066458,  0.04252125, -0.05645508, ...,  0.01315471,
        -0.03183568, -0.04357664],
       [-0.03317154,  0.03252455, -0.02484838, ...,  0.01174421,
         0.05747123,  0.00571021],
       [-0.00166393,  0.00413829, -0.04597083, ...,  0.02008528,
         0.05656242, -0.00161596]], dtype=float32)

In [15]:
dim = vectors.shape[1]

In [16]:
dim

768

# FAISS

In [18]:
import faiss

In [19]:
index = faiss.IndexFlatL2(dim)

In [20]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001FE4B72EEB0> >

In [21]:
index.add(vectors)

In [22]:
search_query = "An apple a day keeps doctor away"

In [24]:
vec = encoder.encode(search_query)

In [25]:
vec.shape

(768,)

# Numpy

In [27]:
import numpy as np

In [28]:
svec = np.array(vec).reshape(1, -1)

In [29]:
svec.shape

(1, 768)

In [30]:
index.search(svec, k=2)

(array([[1.3908098, 1.7193403]], dtype=float32), array([[1, 0]], dtype=int64))

In [31]:
dis, i = index.search(svec, k=2)

In [32]:
dis

array([[1.3908098, 1.7193403]], dtype=float32)

In [33]:
i

array([[1, 0]], dtype=int64)

In [34]:
df.loc[i[0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health